/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActorsRouteImport } from './routes/actors'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ClientRouteImport } from './routes/client'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ActorsIndexRouteImport } from './routes/actors.index'
import { Route as ActorsActorIdRouteImport } from './routes/actors.$actorId'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogKindRouteImport } from './routes/catalog.$kind'
import { Route as FeedsIndexRouteImport } from './routes/feeds.index'
import { Route as FeedsSourcesRouteImport } from './routes/feeds.sources'
import { Route as LibrariesIndexRouteImport } from './routes/libraries.index'
import { Route as LibrariesLibraryIdRouteImport } from './routes/libraries.$libraryId'
import { Route as MetaIndexRouteImport } from './routes/meta.index'
import { Route as MetaMetadataIdRouteImport } from './routes/meta.$metadataId'
import { Route as SavedQueriesQueryIdRouteImport } from './routes/saved-queries.$queryId'
import { Route as CatalogKindFacetIdRouteImport } from './routes/catalog.$kind_.$facetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsRoute = ActorsRouteImport.update({
  id: '/actors',
  path: '/actors',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIndexRoute = ActorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActorsRoute,
} as any)
const ActorsActorIdRoute = ActorsActorIdRouteImport.update({
  id: '/$actorId',
  path: '/$actorId',
  getParentRoute: () => ActorsRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogKindRoute = CatalogKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => CatalogRoute,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedsRoute,
} as any)
const FeedsSourcesRoute = FeedsSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => FeedsRoute,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibrariesRoute,
} as any)
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: '/$libraryId',
  path: '/$libraryId',
  getParentRoute: () => LibrariesRoute,
} as any)
const MetaIndexRoute = MetaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetaRoute,
} as any)
const MetaMetadataIdRoute = MetaMetadataIdRouteImport.update({
  id: '/$metadataId',
  path: '/$metadataId',
  getParentRoute: () => MetaRoute,
} as any)
const SavedQueriesQueryIdRoute = SavedQueriesQueryIdRouteImport.update({
  id: '/saved-queries/$queryId',
  path: '/saved-queries/$queryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogKindFacetIdRoute = CatalogKindFacetIdRouteImport.update({
  id: '/$kind_/$facetId',
  path: '/$kind/$facetId',
  getParentRoute: () => CatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/client': typeof ClientRoute
  '/feeds': typeof FeedsRouteWithChildren
  '/libraries': typeof LibrariesRouteWithChildren
  '/logs': typeof LogsRoute
  '/meta': typeof MetaRouteWithChildren
  '/plugins': typeof PluginsRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/actors/$actorId': typeof ActorsActorIdRoute
  '/catalog/$kind': typeof CatalogKindRoute
  '/feeds/sources': typeof FeedsSourcesRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/meta/$metadataId': typeof MetaMetadataIdRoute
  '/saved-queries/$queryId': typeof SavedQueriesQueryIdRoute
  '/actors/': typeof ActorsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/feeds/': typeof FeedsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/catalog/$kind/$facetId': typeof CatalogKindFacetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/actors/$actorId': typeof ActorsActorIdRoute
  '/catalog/$kind': typeof CatalogKindRoute
  '/feeds/sources': typeof FeedsSourcesRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/meta/$metadataId': typeof MetaMetadataIdRoute
  '/saved-queries/$queryId': typeof SavedQueriesQueryIdRoute
  '/actors': typeof ActorsIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/feeds': typeof FeedsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
  '/meta': typeof MetaIndexRoute
  '/catalog/$kind/$facetId': typeof CatalogKindFacetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/client': typeof ClientRoute
  '/feeds': typeof FeedsRouteWithChildren
  '/libraries': typeof LibrariesRouteWithChildren
  '/logs': typeof LogsRoute
  '/meta': typeof MetaRouteWithChildren
  '/plugins': typeof PluginsRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/actors/$actorId': typeof ActorsActorIdRoute
  '/catalog/$kind': typeof CatalogKindRoute
  '/feeds/sources': typeof FeedsSourcesRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/meta/$metadataId': typeof MetaMetadataIdRoute
  '/saved-queries/$queryId': typeof SavedQueriesQueryIdRoute
  '/actors/': typeof ActorsIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/feeds/': typeof FeedsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/catalog/$kind_/$facetId': typeof CatalogKindFacetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actors'
    | '/catalog'
    | '/client'
    | '/feeds'
    | '/libraries'
    | '/logs'
    | '/meta'
    | '/plugins'
    | '/schedules'
    | '/settings'
    | '/tasks'
    | '/actors/$actorId'
    | '/catalog/$kind'
    | '/feeds/sources'
    | '/libraries/$libraryId'
    | '/meta/$metadataId'
    | '/saved-queries/$queryId'
    | '/actors/'
    | '/catalog/'
    | '/feeds/'
    | '/libraries/'
    | '/meta/'
    | '/catalog/$kind/$facetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/logs'
    | '/plugins'
    | '/schedules'
    | '/settings'
    | '/tasks'
    | '/actors/$actorId'
    | '/catalog/$kind'
    | '/feeds/sources'
    | '/libraries/$libraryId'
    | '/meta/$metadataId'
    | '/saved-queries/$queryId'
    | '/actors'
    | '/catalog'
    | '/feeds'
    | '/libraries'
    | '/meta'
    | '/catalog/$kind/$facetId'
  id:
    | '__root__'
    | '/'
    | '/actors'
    | '/catalog'
    | '/client'
    | '/feeds'
    | '/libraries'
    | '/logs'
    | '/meta'
    | '/plugins'
    | '/schedules'
    | '/settings'
    | '/tasks'
    | '/actors/$actorId'
    | '/catalog/$kind'
    | '/feeds/sources'
    | '/libraries/$libraryId'
    | '/meta/$metadataId'
    | '/saved-queries/$queryId'
    | '/actors/'
    | '/catalog/'
    | '/feeds/'
    | '/libraries/'
    | '/meta/'
    | '/catalog/$kind_/$facetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorsRoute: typeof ActorsRouteWithChildren
  CatalogRoute: typeof CatalogRouteWithChildren
  ClientRoute: typeof ClientRoute
  FeedsRoute: typeof FeedsRouteWithChildren
  LibrariesRoute: typeof LibrariesRouteWithChildren
  LogsRoute: typeof LogsRoute
  MetaRoute: typeof MetaRouteWithChildren
  PluginsRoute: typeof PluginsRoute
  SchedulesRoute: typeof SchedulesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  SavedQueriesQueryIdRoute: typeof SavedQueriesQueryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors': {
      id: '/actors'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof ActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/': {
      id: '/actors/'
      path: '/'
      fullPath: '/actors/'
      preLoaderRoute: typeof ActorsIndexRouteImport
      parentRoute: typeof ActorsRoute
    }
    '/actors/$actorId': {
      id: '/actors/$actorId'
      path: '/$actorId'
      fullPath: '/actors/$actorId'
      preLoaderRoute: typeof ActorsActorIdRouteImport
      parentRoute: typeof ActorsRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/$kind': {
      id: '/catalog/$kind'
      path: '/$kind'
      fullPath: '/catalog/$kind'
      preLoaderRoute: typeof CatalogKindRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof FeedsRoute
    }
    '/feeds/sources': {
      id: '/feeds/sources'
      path: '/sources'
      fullPath: '/feeds/sources'
      preLoaderRoute: typeof FeedsSourcesRouteImport
      parentRoute: typeof FeedsRoute
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/'
      fullPath: '/libraries/'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof LibrariesRoute
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport
      parentRoute: typeof LibrariesRoute
    }
    '/meta/': {
      id: '/meta/'
      path: '/'
      fullPath: '/meta/'
      preLoaderRoute: typeof MetaIndexRouteImport
      parentRoute: typeof MetaRoute
    }
    '/meta/$metadataId': {
      id: '/meta/$metadataId'
      path: '/$metadataId'
      fullPath: '/meta/$metadataId'
      preLoaderRoute: typeof MetaMetadataIdRouteImport
      parentRoute: typeof MetaRoute
    }
    '/saved-queries/$queryId': {
      id: '/saved-queries/$queryId'
      path: '/saved-queries/$queryId'
      fullPath: '/saved-queries/$queryId'
      preLoaderRoute: typeof SavedQueriesQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$kind_/$facetId': {
      id: '/catalog/$kind_/$facetId'
      path: '/$kind/$facetId'
      fullPath: '/catalog/$kind/$facetId'
      preLoaderRoute: typeof CatalogKindFacetIdRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface ActorsRouteChildren {
  ActorsActorIdRoute: typeof ActorsActorIdRoute
  ActorsIndexRoute: typeof ActorsIndexRoute
}

const ActorsRouteChildren: ActorsRouteChildren = {
  ActorsActorIdRoute: ActorsActorIdRoute,
  ActorsIndexRoute: ActorsIndexRoute,
}

const ActorsRouteWithChildren =
  ActorsRoute._addFileChildren(ActorsRouteChildren)

interface CatalogRouteChildren {
  CatalogKindRoute: typeof CatalogKindRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogKindFacetIdRoute: typeof CatalogKindFacetIdRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogKindRoute: CatalogKindRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogKindFacetIdRoute: CatalogKindFacetIdRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface FeedsRouteChildren {
  FeedsSourcesRoute: typeof FeedsSourcesRoute
  FeedsIndexRoute: typeof FeedsIndexRoute
}

const FeedsRouteChildren: FeedsRouteChildren = {
  FeedsSourcesRoute: FeedsSourcesRoute,
  FeedsIndexRoute: FeedsIndexRoute,
}

const FeedsRouteWithChildren = FeedsRoute._addFileChildren(FeedsRouteChildren)

interface LibrariesRouteChildren {
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
}

const LibrariesRouteChildren: LibrariesRouteChildren = {
  LibrariesLibraryIdRoute: LibrariesLibraryIdRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
}

const LibrariesRouteWithChildren = LibrariesRoute._addFileChildren(
  LibrariesRouteChildren,
)

interface MetaRouteChildren {
  MetaMetadataIdRoute: typeof MetaMetadataIdRoute
  MetaIndexRoute: typeof MetaIndexRoute
}

const MetaRouteChildren: MetaRouteChildren = {
  MetaMetadataIdRoute: MetaMetadataIdRoute,
  MetaIndexRoute: MetaIndexRoute,
}

const MetaRouteWithChildren = MetaRoute._addFileChildren(MetaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorsRoute: ActorsRouteWithChildren,
  CatalogRoute: CatalogRouteWithChildren,
  ClientRoute: ClientRoute,
  FeedsRoute: FeedsRouteWithChildren,
  LibrariesRoute: LibrariesRouteWithChildren,
  LogsRoute: LogsRoute,
  MetaRoute: MetaRouteWithChildren,
  PluginsRoute: PluginsRoute,
  SchedulesRoute: SchedulesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  SavedQueriesQueryIdRoute: SavedQueriesQueryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
